In [1]:
import numpy as np
import itertools

# order Y,G,R,B,P
# create a list of all possible permutations 

n = 5
i = np.array(np.indices(n * (2,))).reshape(n, -1)
all_list = i[:, np.argsort(i.sum(0)[::-1], kind='mergesort')].T[::-1]
all_list = all_list[1:] # remove the all off condition
print(all_list)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [1 1 0 0 0]
 [1 0 1 0 0]
 [1 0 0 1 0]
 [1 0 0 0 1]
 [0 1 1 0 0]
 [0 1 0 1 0]
 [0 1 0 0 1]
 [0 0 1 1 0]
 [0 0 1 0 1]
 [0 0 0 1 1]
 [1 1 1 0 0]
 [1 1 0 1 0]
 [1 1 0 0 1]
 [1 0 1 1 0]
 [1 0 1 0 1]
 [1 0 0 1 1]
 [0 1 1 1 0]
 [0 1 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [1 1 1 1 0]
 [1 1 1 0 1]
 [1 1 0 1 1]
 [1 0 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]]


In [2]:
output = []

for my_list in all_list:
    
    simul = 'T'
    
    Y = my_list[0]
    G = my_list[1]
    R = my_list[2]
    B = my_list[3]
    P = my_list[4]
            
    while simul == 'T':
        # C1
        if Y==1 and Y+R ==1:
            simul ='F'
        
        if R == 1 and G == 1:
            simul ='F'
            
        if B+G == 1:
            simul ='F'
            
        if B + P == 0:
            simul ='F'
            
        if P == 1 and B + Y < 2:
            simul ='F'
        
        if simul == 'T':
            output.append(list(my_list))
            print (my_list,simul)
            simul ='F'

[0 1 0 1 0] T
